### ISSUE TITLE
 server not visible

### ISSUE THREAD

**Issue by hiro1234omochi** [rtm516/MCXboxBroadcast#14]
I get "[Geyser-Spigot] [MCXboxBroadcast] Created Xbox session!" but no server is displayed. What should I do? I have linked with the xbox displayed on the console.

**Comment by hiro1234omochi** [comment]
It is introduced as an extended function of geysermc.
I haven't done any configuration for this extension other than linking it to xbox.

**Comment by rtm516** [comment]
Are you using a different account on the server and your xbox? If you use just 1 account it wont show up.

**Comment by hiro1234omochi** [comment]
of course.
I used a subaccount.

**Comment by rtm516** [comment]
Make sure the account doesnt have any family settings or privacy settings restricting it and make sure you are full xbox friends

**Comment by PizzaThatCodes** [comment]
Have you tried logging into the subaccount and accepting the friend request from your main? I've had the same issue where it shows that its started but never showed up since there is not the option of AutoFriend on the geyser extension so it won't accept the request automatically and show up in the friends tab.

So my answer is to try accepting the request on the sub account and let me know if the error still persists.

If that was the issue there is a fix coming out soon (pull request #21 ) that will have the AutoFriend option available for the Geyser Extension.

**Comment by hiro1234omochi** [comment]
@PizzaThatCodes @rtm516 
After manually granting the friend request, the server showed up and I was able to enter.
I am looking forward to the implementation of automatic approval of friend requests.
Thank you for your support.
