### ISSUE TITLE
Extension Doesn't Autofollow

### ISSUE THREAD

**Issue by slash1div** [rtm516/MCXboxBroadcast#16]
Self explanatory. Due to this, other people are unable to join from the friends tab.

I'm using this on a Waterfall proxy if this has anything to do with it.
Works perfect when they get added as a friend manually, this is the only issue I've had.

**Comment by slash1div** [comment]
It is being ran as an extension, not standalone.

**Comment by PizzaThatCodes** [comment]
Added a fix for this, just waiting on it being merged #21

**Comment by slash1div** [comment]
Ooh nice. Do you have a jar file out that you could possibly put as a release for the public for the time being?

**Comment by PizzaThatCodes** [comment]
> Ooh nice. Do you have a jar file out that you could possibly put as a release for the public for the time being? I'm using a separate machine for my MCXboxBroadcast as standalone and the ping is very unstable as its under multiple proxies.

Sure! I'll have the .jar in the repository I forked while we wait for rtm516 to merge it on here. 

Here is the link:
https://github.com/PizzaThatCodes/MCXboxBroadcast/releases/tag/release

**Comment by SonnenPingu** [comment]
!! Will there be an update on this soon?

The jar file 21 is Outdate. But it works more badly than right @rtm516

**Comment by PizzaThatCodes** [comment]
> 

How exactly is the Jar file from Pull Request 21 outdated compared to the main branch? Its on the newest version of MCXboxBroadcast but has autofriend feature working. Also how does it work worse than the main branch exactly? If I know what is wrong I can try to fix it.

**Comment by SonnenPingu** [comment]
Thanks for the info and your answer.
The outdate referred to the fact that there is already 22 at jenkis. But
I've seen that between 21 and 22 had not changed anything. Lol

But maybe you can help me with this:

[ INFO] [Geyser-Spigot] [MCXboxBroadcast] Connection to websocket lost,
re-creating session... All the time.

And


By the way, it doesn't really work well either
PlaystationUser Can't find my account within minecraft. Although I rather
have the assumption that this is due to Sony and not to the extensions.






PizzaThatCodes ***@***.***> schrieb am Mo., 29. Mai 2023,
20:32:
